language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6

env:
  global:
    - ES_VER=1.3.4
    - ES_MAPPER_ATTACHMENTS_VER=2.0.0.RC1
    - ES_TRANSPORT_THRIFT_VER=2.0.0
    - ES_GEOCLUSTER_FACET_VER=0.0.10
    - ES_WAIT_ON_MAPPING_CHANGE=true
    - MEMCACHE_VER=3.0.8
  matrix:
    - ES_REQUIRE=dev
    - ES_REQUIRE=no-dev
    
services:
    - memcached

before_script:
    - composer self-update
    - composer --${ES_REQUIRE} --prefer-source install
    - ./test/bin/install_php_memcache.sh
    - ./test/bin/run_elasticsearch.sh
    - ./test/bin/run_proxy.sh

script:
    - mkdir -p build/logs
    - phpunit --coverage-clover build/logs/clover.xml -c test/

after_script:
    - ./test/bin/show_logs.sh
    - php vendor/bin/coveralls -v
